apiVersion: batch/v1
kind: CronJob
metadata:
  name: job-clean
  namespace: tools
  uid: "8abb95d2-2eaa-4f2c-9d6e-1bd3c6fce510"
spec:
  schedule: "1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: job-clean
            image: agnerft/nginx:1.4
          restartPolicy: OnFailure