apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-json-server
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/data/teste
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-json-server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi